GET http://api.steampowered.com/ISteamUser/GetFriendList/v0001/?key=1F50BBFAE8B34A4D5BDDA8B2FDB08B18&steamid=76561198069504185&relationship=friend

###

GET https://open.faceit.com/data/v4/search/players?nickname=Mammothus&offset=0&limit=20
Authorization: Bearer 949f8236-b9de-4d42-933e-5e7f8ce50ed2

###
GET https://open.faceit.com/data/v4/players/87307577-6381-40a5-a7c2-97ba3ec94d55
Authorization: Bearer 949f8236-b9de-4d42-933e-5e7f8ce50ed2
